# Compile stage
FROM golang:1.23-alpine3.20 as builder
WORKDIR /app
COPY src/go.mod src/go.sum ./
COPY src/main/*.go  ./main/
COPY src/hvac/*.go  ./hvac/
COPY src/light/*.go ./light/
RUN go mod download && go mod tidy && cd main; CGO_ENABLED=0 GOOS=linux go build -o /warm_home ./...

# Execution stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /warm_home .

# Run
EXPOSE 8080/tcp
ENTRYPOINT ["/warm_home"]
