# Compile stage
FROM golang:1.23-alpine3.20 as builder
WORKDIR /app
COPY src/go.mod src/go.sum ./
COPY src/telemetry.lights/*.go ./telemetry/
RUN go mod download && go mod tidy && cd telemetry; CGO_ENABLED=0 GOOS=linux go build -o /warm_home_telemetry ./...

# Execution stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /warm_home_telemetry .

# Run
ENTRYPOINT ["/warm_home_telemetry"]
