apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kong-gateway
  name: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kong-gateway
    spec:
      containers:
        - env:
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_GUI_URL
              value: http://localhost:8002
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: postgres-kong.default
            - name: KONG_PG_PASSWORD
              value: kongpass
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
          image: kong/kong-gateway:latest
          livenessProbe:
            exec:
              command: ["kong", "health"]
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: kong-gateway
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
            - containerPort: 8444
              protocol: TCP
            - containerPort: 8002
              protocol: TCP
            - containerPort: 8445
              protocol: TCP
            - containerPort: 8003
              protocol: TCP
            - containerPort: 8004
              protocol: TCP
            - containerPort: 8005
              protocol: TCP
            - containerPort: 8006
              protocol: TCP
            - containerPort: 8007
              protocol: TCP
      restartPolicy: Always
