apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-kong
  name: postgres-kong
spec:
  replicas: 1
#  hostname: postgres-kong
  selector:
    matchLabels:
      io.kompose.service: postgres-kong
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres-kong
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_PASSWORD
              value: kongpass
            - name: POSTGRES_USER
              value: kong
          image: postgres:alpine
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: postgres-kong
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "536870912"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: kong-data
      restartPolicy: Always
      volumes:
        - name: kong-data
          persistentVolumeClaim:
            claimName: kong-data
