apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: warm-home-hvac
  name: warm-home-hvac
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: warm-home-hvac
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: warm-home-hvac
    spec:
      containers:
        - env:
            - name: APP_PORT
              value: "8080" # match app-port value
            - name: DB_HOST
              value: postgres-hvac.default
            - name: DB_NAME
              value: warm_home_hvac
            - name: DB_PASS
              value: hvac_password
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: hvac_user
          image: warm-home-hvac
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /livez
              port: app-port
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: app-port
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: warm-home-hvac
          ports:
            - name: app-port
              containerPort: 8080
      restartPolicy: Always
